# Project 2 Hospital

In [2]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)

def generate_arrival_rate (Lam):
    patients_to_time_t = np.random.poisson(lam= Lam)
    return patients_to_time_t

def generate_ward_A_length_of_stay(t):
    lam1= -(1/3650)*t**2 + (1/10)*t 
    arriaval_rate =generate_arrival_rate (lam1)
    Ward_A_lenght_of_stay = np.random.lognormal(mean=np.log(4*np.sqrt(2)),sigma=np.sqrt(np.log(2)), size=int(arriaval_rate) )
    N_patients_A = len(Ward_A_lenght_of_stay)
    return Ward_A_lenght_of_stay, N_patients_A

def generate_ward_B_length_of_stay(t):
    lam2 = 1/5*( -(1/3650)*t**2 + (1/10)*t )
    arriaval_rate = generate_arrival_rate(lam2)
    Ward_B_lenght_of_stay = np.random.lognormal(mean=np.log(6*np.sqrt(2)),sigma=np.sqrt(np.log(2)), size=int(arriaval_rate ))
    N_patients_B = len(Ward_B_lenght_of_stay)
    return Ward_B_lenght_of_stay, N_patients_B


def generate_ward_C_length_of_stay(t):
    arriaval_rate = generate_arrival_rate(6)
    Ward_C_lenght_of_stay = np.random.lognormal(mean=np.log(5*np.sqrt(2)),sigma=np.sqrt(np.log(2)), size=int(arriaval_rate ))
    N_patients_C = len(Ward_C_lenght_of_stay)
    return Ward_C_lenght_of_stay, N_patients_C



def generate_length_of_stay(t, Ward):
    if Ward=='A':
        return generate_ward_A_length_of_stay(t)
    if Ward=='B':
        return generate_ward_B_length_of_stay(t)
    if Ward=='C':
        return generate_ward_C_length_of_stay(t)

In [3]:
lenght_of_stay_C, arrivals_C = generate_length_of_stay(150,'C')
lenght_of_stay_C, arrivals_C

(array([ 8.92029143, 16.40064499,  4.35968032,  4.56664572,  4.39429149,
         3.27612747]),
 6)

In [ ]:
np.random.seed(42)
def run_Hospital_simulation(bed_distribution):
    A_beds, B_beds, C_beds = bed_distribution
    times = np.arange(1,365,1)

    # Counts everyone who tried to get into Ward X but couldnt
    blocked_WardA = 0
    blocked_WardB = 0 #tæller ikke
    blocked_WardC = 0

    # Counts everyone who was transfored to another hospital
    next_free_bed_A = np.zeros((A_beds))
    next_free_bed_B = np.zeros((B_beds))
    next_free_bed_C = np.zeros((C_beds))
    total_arrivals_list = []

    full_A = full_B = full_C = 0
    # Counts everyone who was transfored to another hospital
    relocated_A = relocated_B = relocated_C = 0
    attempts_WardA = 0

    arrivals_total_A = 0
    arrivals_total_B = 0
    arrivals_total_C = 0

    util_A = []
    util_B = []
    util_C = []

    for t in times:
        lenght_of_stay_A, arrivals_A = generate_length_of_stay(t,'A')
        lenght_of_stay_B, arrivals_B = generate_length_of_stay(t,'B')
        lenght_of_stay_C, arrivals_C = generate_length_of_stay(t,'C')
        total_arrivals = arrivals_A+arrivals_B+arrivals_C
        #print(f"t={t} Lengt of stay A:{len(lenght_of_stay_A)}, B:{len(lenght_of_stay_B)} , C:{len(lenght_of_stay_C)}")

        # estimate free beds
        available_bedsA = next_free_bed_A <= t
        available_bedsB = next_free_bed_B <= t
        available_bedsC = next_free_bed_C <= t
        arrivals_total_A += arrivals_A
        arrivals_total_B += arrivals_B
        arrivals_total_C += arrivals_C

        # kan man sorte længderne så vi blokerer beds ift længde?
        
        #_--------------------------
        # Ward B first! 
        j = -1
        indexes = np.where(available_bedsB)[0]
        admitted_B = min(len(lenght_of_stay_B), len(indexes))

        if np.any(available_bedsB) and len(lenght_of_stay_B)!=0 :
            for j,ib in enumerate(indexes):
                if j < len(lenght_of_stay_B):
                    next_free_bed_B[ib] = t+ lenght_of_stay_B[j]
                else: 
                    j -= 1
        diff_B = arrivals_B - admitted_B
        blocked_WardB += diff_B
        full_B += diff_B

        B_overflow_los = np.array([])

        if diff_B > 0:
            B_overflow_los = lenght_of_stay_B[j+1:]
            lenght_of_stay_A = np.append(lenght_of_stay_A,B_overflow_los)

        #_--------------------------
        # Ward A
        indexes = np.where(available_bedsA)[0]
        admitted_A = min(len(lenght_of_stay_A), len(indexes))
        attempts_WardA += len(lenght_of_stay_A) 

        j = -1
        if np.any(available_bedsA) and len(lenght_of_stay_A)!=0:
            for j,ia in enumerate(indexes):
                if j < len(lenght_of_stay_A):
                    next_free_bed_A[ia] = t+ lenght_of_stay_A[j]
                else: 
                    j -= 1
        diff_A = len(lenght_of_stay_A) - admitted_A
        blocked_WardA += diff_A
    
        n_B_try_A = diff_B
        n_A_try_A = arrivals_A

        A_admitted_A = min(n_A_try_A, admitted_A)
        B_admitted_A = admitted_A - A_admitted_A

        relocated_B += n_B_try_A - B_admitted_A
        relocated_A += n_A_try_A - A_admitted_A

        full_A += n_A_try_A - A_admitted_A

        #_--------------------------
        # Ward C
        indexes = np.where(available_bedsC)[0]
        admitted_C = min(len(lenght_of_stay_C), len(indexes))
        j = -1
        if np.any(available_bedsC) and len(lenght_of_stay_C)!=0:
            for j,ic in enumerate(indexes):
                if j < len(lenght_of_stay_C):
                    next_free_bed_C[ic] = t + lenght_of_stay_C[j]
                else: 
                    j -= 1
        diff_C = arrivals_C - admitted_C
        blocked_WardC += diff_C
        full_C += diff_C      
        relocated_C += diff_C

        # Update lists
        total_arrivals_list.append(total_arrivals)

        # Utilization of beds
        util_A.append(np.mean(next_free_bed_A > t))
        util_B.append(np.mean(next_free_bed_B > t))
        util_C.append(np.mean(next_free_bed_C > t))

    results = { 
        "prob_full_A": full_A / arrivals_total_A,
        "prob_full_B": full_B / arrivals_total_B,
        "prob_full_C": full_C / arrivals_total_C,

        "relocated_A": relocated_A,
        "relocated_B": relocated_B,
        "relocated_C": relocated_C,
        "relocated_total": relocated_A + relocated_B + relocated_C,

        "utilization_A": np.mean(util_A),
        "utilization_B": np.mean(util_B),
        "utilization_C": np.mean(util_C),

        "blocked_WardA": blocked_WardA,
        "blocked_WardB": blocked_WardB,
        "blocked_WardC": blocked_WardC,

        "arrivals_A": arrivals_total_A,
        "arrivals_B": arrivals_total_B,
        "arrivals_C": arrivals_total_C,

        "total_arrivals_list": total_arrivals_list
    }

    return results

    

A_beds = 30
B_beds = 15
C_beds = 30


results  = run_Hospital_simulation((A_beds,B_beds, C_beds ))

In [7]:
results['blocked_WardA'], results['utilization_A']

(1157, np.float64(0.8786630036630038))

In [9]:
def grid_search_beds(total_beds=75, n_reps=100):
    results = []

    for A_beds in range(1, total_beds):
        for B_beds in range(1, total_beds - A_beds):
            C_beds = total_beds - A_beds - B_beds

            prob_full_A_values = []
            prob_full_B_values = []
            prob_full_C_values = []

            relocated_A_values = []
            relocated_B_values = []
            relocated_C_values = []
            relocated_total_values = []

            util_A_values = []
            util_B_values = []
            util_C_values = []

            for rep in range(n_reps):
                res = run_Hospital_simulation(
                    (A_beds, B_beds, C_beds)
                )

                prob_full_A_values.append(res["prob_full_A"])
                prob_full_B_values.append(res["prob_full_B"])
                prob_full_C_values.append(res["prob_full_C"])

                relocated_A_values.append(res["relocated_A"])
                relocated_B_values.append(res["relocated_B"])
                relocated_C_values.append(res["relocated_C"])
                relocated_total_values.append(res["relocated_total"])

                util_A_values.append(res["utilization_A"])
                util_B_values.append(res["utilization_B"])
                util_C_values.append(res["utilization_C"])

            results.append({
                "A_beds": A_beds,
                "B_beds": B_beds,
                "C_beds": C_beds,

                "mean_prob_full_A": np.mean(prob_full_A_values),
                "mean_prob_full_B": np.mean(prob_full_B_values),
                "mean_prob_full_C": np.mean(prob_full_C_values),

                "mean_relocated_A": np.mean(relocated_A_values),
                "mean_relocated_B": np.mean(relocated_B_values),
                "mean_relocated_C": np.mean(relocated_C_values),
                "mean_relocated_total": np.mean(relocated_total_values),

                "sd_relocated_total": np.std(relocated_total_values, ddof=1),

                "mean_utilization_A": np.mean(util_A_values),
                "mean_utilization_B": np.mean(util_B_values),
                "mean_utilization_C": np.mean(util_C_values)
            })

    return results

In [12]:
import pandas as pd
coarse_results = grid_search_beds(total_beds=75,n_reps=1)

coarse_df = pd.DataFrame(coarse_results)

top20 = coarse_df.sort_values("mean_relocated_total").head(20)

top20

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/_core/_methods.py:219: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/_core/_methods.py:211: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

,A_beds,B_beds,C_beds,mean_prob_full_A,mean_prob_full_B,mean_prob_full_C,mean_relocated_A,mean_relocated_B,mean_relocated_C,mean_relocated_total,sd_relocated_total,mean_utilization_A,mean_utilization_B,mean_utilization_C
2269,45,4,26,0.274085,0.761446,0.563636,569.0,218.0,1178.0,1965.0,NaN,0.845849,0.921016,0.987320
2106,40,1,34,0.368349,0.954545,0.429713,803.0,310.0,914.0,2027.0,NaN,0.869918,0.923077,0.979315
1578,27,6,42,0.539860,0.676056,0.298095,1158.0,261.0,626.0,2045.0,NaN,0.897232,0.887821,0.958006
1923,35,3,37,0.409729,0.844340,0.410593,876.0,285.0,907.0,2068.0,NaN,0.891994,0.893773,0.982031
1573,27,1,47,0.536872,0.950226,0.258741,1143.0,374.0,555.0,2072.0,NaN,0.904457,0.914835,0.962065
2173,42,1,32,0.346353,0.930131,0.486144,736.0,309.0,1035.0,2080.0,NaN,0.861983,0.950549,0.981971
2110,40,5,30,0.368397,0.703125,0.476728,809.0,258.0,1014.0,2081.0,NaN,0.844093,0.891209,0.987363
2071,39,1,35,0.366864,0.933333,0.428963,806.0,336.0,939.0,2081.0,NaN,0.892223,0.920330,0.982025
1885,34,5,36,0.442593,0.681499,0.394379,983.0,257.0,842.0,2082.0,NaN,0.880171,0.840110,0.976954
1327,22,5,48,0.595315,0.713287,0.234382,1296.0,287.0,499.0,2082.0,NaN,0.920455,0.891758,0.948088
1525,26,1,48,0.555708,0.915767,0.230877,1212.0,380.0,495.0,2087.0,NaN,0.904691,0.939560,0.951122
1765,31,11,33,0.421840,0.418182,0.462406,931.0,173.0,984.0,2088.0,NaN,0.896402,0.817682,0.984432
1999,37,2,36,0.417383,0.852941,0.413827,922.0,317.0,850.0,2089.0,NaN,0.867983,0.907967,0.975656
1961,36,2,37,0.408007,0.880795,0.397573,907.0,330.0,852.0,2089.0,NaN,0.884386,0.925824,0.976834
2326,47,4,24,0.253165,0.748219,0.625000,560.0,215.0,1315.0,2090.0,NaN,0.833820,0.916209,0.990270
2109,40,4,31,0.364096,0.768539,0.475034,793.0,261.0,1037.0,2091.0,NaN,0.866758,0.885989,0.982099
1436,24,11,40,0.582805,0.379562,0.312857,1288.0,146.0,657.0,2091.0,NaN,0.889995,0.786713,0.964766
2377,49,2,24,0.241363,0.868159,0.610254,510.0,240.0,1345.0,2095.0,NaN,0.830175,0.909341,0.991987
1799,32,2,41,0.475261,0.865566,0.344011,1047.0,310.0,741.0,2098.0,NaN,0.890110,0.916209,0.974069
994,16,5,54,0.715837,0.652500,0.126091,1582.0,258.0,260.0,2100.0,NaN,0.928400,0.880769,0.935847

In [ ]:
def rerun_candidates(candidates_df, n_reps=75):
    results = []

    for _, row in candidates_df.iterrows():
        A_beds = int(row["A_beds"])
        B_beds = int(row["B_beds"])
        C_beds = int(row["C_beds"])

        candidate_results = []

        for rep in range(n_reps):
            res = run_Hospital_simulation(
                (A_beds, B_beds, C_beds)
            )
            candidate_results.append(res)

        results.append({
            "A_beds": A_beds,
            "B_beds": B_beds,
            "C_beds": C_beds,

            "mean_prob_full_A": np.mean([r["prob_full_A"] for r in candidate_results]),
            "mean_prob_full_B": np.mean([r["prob_full_B"] for r in candidate_results]),
            "mean_prob_full_C": np.mean([r["prob_full_C"] for r in candidate_results]),

            "mean_relocated_A": np.mean([r["relocated_A"] for r in candidate_results]),
            "mean_relocated_B": np.mean([r["relocated_B"] for r in candidate_results]),
            "mean_relocated_C": np.mean([r["relocated_C"] for r in candidate_results]),
            "mean_relocated_total": np.mean([r["relocated_total"] for r in candidate_results]),

            "sd_relocated_total": np.std(
                [r["relocated_total"] for r in candidate_results],
                ddof=1
            ),

            "mean_utilization_A": np.mean([r["utilization_A"] for r in candidate_results]),
            "mean_utilization_B": np.mean([r["utilization_B"] for r in candidate_results]),
            "mean_utilization_C": np.mean([r["utilization_C"] for r in candidate_results])
        })

    return pd.DataFrame(results)

,A_beds,B_beds,C_beds,mean_prob_full_A,mean_prob_full_B,mean_prob_full_C,mean_relocated_A,mean_relocated_B,mean_relocated_C,mean_relocated_total,sd_relocated_total,mean_utilization_A,mean_utilization_B,mean_utilization_C
0,45,4,26,0.318194,0.759425,0.577035,707.40,254.27,1263.75,2225.42,77.151848,0.845711,0.891065,0.989330
1,40,1,34,0.381458,0.938467,0.455267,847.08,325.67,998.27,2171.02,65.799509,0.872944,0.925220,0.981972
2,27,6,42,0.543698,0.653602,0.336684,1207.40,268.14,736.41,2211.95,61.935022,0.898664,0.867738,0.971014
3,35,3,37,0.437045,0.820900,0.409021,969.65,309.33,892.80,2171.78,71.308064,0.880485,0.904240,0.977718
4,27,1,47,0.547457,0.937945,0.261910,1212.91,372.76,572.92,2158.59,67.968218,0.911620,0.923819,0.960433
5,42,1,32,0.359562,0.938565,0.488128,799.52,317.09,1067.67,2184.28,75.625884,0.867357,0.928901,0.983925
6,40,5,30,0.368125,0.706987,0.518389,816.56,254.29,1130.26,2201.11,74.279692,0.857434,0.874522,0.985692
7,39,1,35,0.396928,0.935871,0.441405,882.22,329.32,965.74,2177.28,85.162125,0.877498,0.930659,0.980557
8,34,5,36,0.448798,0.709547,0.426477,1000.85,275.32,935.14,2211.31,77.770537,0.879558,0.880747,0.979506
9,22,5,48,0.618063,0.702491,0.251420,1372.72,293.76,551.05,2217.53,74.749339,0.916774,0.878780,0.958794
10,26,1,48,0.564551,0.937322,0.253299,1256.14,376.50,553.81,2186.45,74.313066,0.914361,0.925412,0.959149
11,31,11,33,0.478119,0.409937,0.474331,1059.17,169.12,1038.32,2266.61,78.146960,0.880924,0.800717,0.982846
12,37,2,36,0.416678,0.879286,0.425982,925.95,321.84,932.51,2180.30,79.050872,0.877426,0.916168,0.979103
13,36,2,37,0.424683,0.880596,0.408875,939.25,321.99,892.62,2153.86,72.957442,0.881683,0.910879,0.978006
14,47,4,24,0.295294,0.762739,0.613660,654.47,243.93,1341.72,2240.12,70.338759,0.837567,0.891374,0.990403
15,40,4,31,0.378064,0.759758,0.501912,844.47,268.56,1094.02,2207.05,71.861451,0.861657,0.889341,0.984313
16,24,11,40,0.583402,0.421388,0.365186,1294.40,180.66,799.01,2274.07,80.009249,0.904090,0.801613,0.974240
17,49,2,24,0.284860,0.876932,0.612032,636.40,269.66,1334.70,2240.76,77.701594,0.840212,0.914698,0.990071
18,32,2,41,0.479059,0.877472,0.353431,1063.27,336.72,773.79,2173.78,67.737995,0.893530,0.915343,0.972625
19,16,5,54,0.715013,0.707725,0.170691,1592.55,307.17,373.75,2273.47,70.144505,0.934548,0.879555,0.942029

In [14]:
# find bedste candi
final_df = rerun_candidates(top20, n_reps=75)
final_best = final_df.loc[final_df["mean_relocated_total"].idxmin()]
final_best

A_beds                    32.000000
B_beds                     2.000000
C_beds                    41.000000
mean_prob_full_A           0.477296
mean_prob_full_B           0.875707
mean_prob_full_C           0.349500
mean_relocated_A        1056.613333
mean_relocated_B         333.093333
mean_relocated_C         762.546667
mean_relocated_total    2152.253333
sd_relocated_total        83.993902
mean_utilization_A         0.893907
mean_utilization_B         0.915403
mean_utilization_C         0.973029
Name: 18, dtype: float64

In [15]:
final_df

,A_beds,B_beds,C_beds,mean_prob_full_A,mean_prob_full_B,mean_prob_full_C,mean_relocated_A,mean_relocated_B,mean_relocated_C,mean_relocated_total,sd_relocated_total,mean_utilization_A,mean_utilization_B,mean_utilization_C
0,45,4,26,0.317245,0.758943,0.582131,702.240000,251.613333,1274.746667,2228.600000,76.174941,0.843491,0.895311,0.988862
1,40,1,34,0.380089,0.937426,0.452240,845.653333,324.853333,988.213333,2158.720000,92.807205,0.871680,0.926630,0.981267
2,27,6,42,0.545720,0.653629,0.336879,1212.120000,270.946667,736.786667,2219.853333,69.391699,0.899464,0.872473,0.971371
3,35,3,37,0.440790,0.819829,0.410475,979.133333,307.773333,898.280000,2185.186667,77.949688,0.879960,0.903187,0.978579
4,27,1,47,0.548856,0.937473,0.263408,1217.173333,375.320000,577.080000,2169.573333,79.526670,0.911533,0.925568,0.961632
5,42,1,32,0.358967,0.938163,0.489417,798.240000,319.106667,1072.253333,2189.600000,78.752778,0.864706,0.924725,0.984136
6,40,5,30,0.374033,0.705600,0.517778,830.560000,254.053333,1130.786667,2215.400000,78.457770,0.860360,0.878821,0.985822
7,39,1,35,0.394534,0.937100,0.440643,875.280000,324.533333,961.440000,2161.253333,85.354443,0.874719,0.927289,0.980842
8,34,5,36,0.448535,0.708702,0.425721,992.613333,272.413333,930.480000,2195.506667,74.216151,0.875168,0.878557,0.979359
9,22,5,48,0.618596,0.706432,0.249871,1373.400000,300.600000,546.200000,2220.200000,88.501947,0.915528,0.884278,0.958460
10,26,1,48,0.561892,0.939187,0.253036,1245.653333,376.186667,553.960000,2175.800000,87.475247,0.913632,0.928388,0.959357
11,31,11,33,0.480536,0.415348,0.472751,1064.920000,172.093333,1033.626667,2270.640000,82.280115,0.878033,0.799867,0.982772
12,37,2,36,0.416996,0.877561,0.426321,927.746667,323.360000,934.666667,2185.773333,80.794797,0.879965,0.913297,0.979581
13,36,2,37,0.425486,0.877624,0.411108,942.933333,323.080000,900.053333,2166.066667,76.349717,0.878916,0.914927,0.978061
14,47,4,24,0.297543,0.757245,0.612614,659.200000,241.293333,1336.226667,2236.720000,79.955319,0.837748,0.890421,0.990398
15,40,4,31,0.376385,0.758285,0.504114,836.186667,270.533333,1104.226667,2210.946667,87.798586,0.861527,0.889670,0.983873
16,24,11,40,0.585500,0.420359,0.365535,1300.986667,180.253333,799.360000,2280.600000,75.025761,0.904698,0.802474,0.973975
17,49,2,24,0.281818,0.877066,0.613667,626.706667,267.840000,1346.413333,2240.960000,67.845699,0.839581,0.916886,0.990142
18,32,2,41,0.477296,0.875707,0.349500,1056.613333,333.093333,762.546667,2152.253333,83.993902,0.893907,0.915403,0.973029
19,16,5,54,0.712876,0.703150,0.169459,1583.906667,302.320000,372.026667,2258.253333,81.831748,0.935561,0.879092,0.941136

In [23]:
# kører det hele igen for at få alle paramentre ud
n_reps = 100

all_results = []

for _ in range(n_reps):
    all_results.append(
        run_Hospital_simulation((32,2,41))
    )
summary = {
    key: np.mean([r[key] for r in all_results])
    for key in [
        "prob_full_A",
        "prob_full_B",
        "prob_full_C",
        "relocated_A",
        "relocated_B",
        "relocated_C",
        "relocated_total",
        "utilization_A",
        "utilization_B",
        "utilization_C"
    ]
}

summary

{'prob_full_A': np.float64(0.47629176720337774),
 'prob_full_B': np.float64(0.8772589966158222),
 'prob_full_C': np.float64(0.3514699232730187),
 'relocated_A': np.float64(1053.09),
 'relocated_B': np.float64(332.87),
 'relocated_C': np.float64(767.95),
 'relocated_total': np.float64(2153.91),
 'utilization_A': np.float64(0.8934177541208791),
 'utilization_B': np.float64(0.9131593406593406),
 'utilization_C': np.float64(0.9718440096488876)}

In [24]:
# Probability of full ward on arrival
summary['prob_full_A' ], summary['prob_full_B' ], summary['prob_full_C' ]

(np.float64(0.47629176720337774),
 np.float64(0.8772589966158222),
 np.float64(0.3514699232730187))

In [25]:
# mean relocated patiens
summary['relocated_A' ], summary['relocated_B' ], summary['relocated_C' ], summary['relocated_total']

(np.float64(1053.09),
 np.float64(332.87),
 np.float64(767.95),
 np.float64(2153.91))

In [26]:
# mean utilization
summary['utilization_A' ], summary['utilization_B' ], summary['utilization_C' ]

(np.float64(0.8934177541208791),
 np.float64(0.9131593406593406),
 np.float64(0.9718440096488876))